// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SupercarJava;

/************************************************************/
/**
 * 
 */
public class Commandes {
	/**
	 * 
	 */
	 private int IDCommande;
	/**
	 * 
	 */
	 private int IDEntrepot;
		/**
		 * 
		 */
	 private String DateCommande;
	/**
	 * 
	 */
	private String NomModele;
	/**
	 * 
	 */
	private String PaysDorigine;
	/**
	 * 
	 */
	private String NomEmp;
	/**
	 * 
	 */
	private int Quantite;
	/**
	 * 
	 */
	private int PrixCommande;
	/**
	 * 
	 */
	public Stock stock;

	/**
	 * 
	 */
	public int getIDCommande() {
		return IDCommande;
	}

	/**
	 * 
	 */
	
	public int getIDEntrepot() {
		return IDEntrepot;
	}

	/**
	 * 
	 */
	public String getDateCommande() {
		return DateCommande;
	}

	/**
	 * 
	 */
	public String getNomModele() {
		return NomModele;
	}

	/**
	 * 
	 */
	public String getPaysDorigine() {
		return PaysDorigine;
	}

	/**
	 * 
	 */
	public String getNomEmp() {
		return NomEmp;
	}

	/**
	 * 
	 */
	public int getQuantite() {
		return Quantite;
	}

	/**
	 * 
	 */
	public int getPrixCommande() {
		return PrixCommande;
	}

	/**
	 * 
	 */
	public void createCommande(int Entrepot, String Date, String NomModele,String Pays, String NomEmp, int Quantite, int Prix) {
		this.IDEntrepot = Entrepot;
		this.DateCommande =Date;
		this.NomModele = NomModele;
		this.PaysDorigine = Pays;
		this.NomEmp = NomEmp;
		this.Quantite = Quantite;
		this.PrixCommande = Prix;
		
	}

	/**
	 * 
	 */
	public void updateCommande(int ID, int Entrepot, String Date, String NomModele,String Pays, String NomEmp, int Quantite, int Prix) {
	    this.IDCommande = ID;
		this.IDEntrepot = Entrepot;
		this.DateCommande =Date;
		this.NomModele = NomModele;
		this.PaysDorigine = Pays;
		this.NomEmp = NomEmp;
		this.Quantite = Quantite;
		this.PrixCommande = Prix;
		
	}
};
