// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SupercarJava;

/************************************************************/
/**
 * 
 */
public class Entrepot {
	/**
	 * 
	 */
	private int IDEntrepot;
	/**
	 * 
	 */
	private String Adresse;
	/**
	 * 
	 */
	private int NbVoitures;
	/**
	 * 
	 */
	public Stock stock;
	/**
	 * 
	 */
	public Commandes commandes;

	/**
	 * 
	 */
	public int getIDEntrepot() {
		return IDEntrepot;
	}

	/**
	 * 
	 */
	public String getAdresse() {
		return Adresse;
	}

	/**
	 * 
	 */
	public int getNbVoitures() {
		return NbVoitures;
	}
	/**
	 * 
	 */
	public void updateNbVoitures(int ID, int NewNbVoitures) {
		 this.IDEntrepot = ID;
	     this.NbVoitures = NewNbVoitures;
	}
};
