// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package SupercarJava;

/************************************************************/
/**
 * 
 */
public class Stock {
	/**
	 * 
	 */
	private int IDStock;
	/**
	 * 
	 */
	private String NomModele;
	/**
	 * 
	 */
	public int PrixModele;
	/**
	 * 
	 */
	private String PaysDorigine;
	/**
	 * 
	 */
	private int Quantite;

	/**
	 * 
	 */
	private int IDEntrepot;

	/**
	 * 
	 */
	public int getIDStock() {
		return IDStock;
	}

	/**
	 * 
	 */
	public String getNomModele() {
		return NomModele;
	}

	/**
	 * 
	 */
	public int getPrixModele() {
		return PrixModele;
	}
	/**
	 * 
	 */
	public String getPaysDorigine() {
		return PaysDorigine;
	}

	/**
	 * 
	 */
	public int getQuantite() {
	    return Quantite;
	}

	/**
	 * 
	 */
	public int getIDEntrepot() {
	    return IDEntrepot;
	}
	/**
	 * 
	 */
	public void setStock(String Modele, int PrixModele, String Pays, int NewQuantite, int Entrepot) {
		this.NomModele = Modele;
		this.PrixModele = PrixModele;
		this.PaysDorigine = Pays;
	   this.Quantite = NewQuantite;
	   this.IDEntrepot = Entrepot;
	}
};
